# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "calculator.CalculatorRequest" do
    repeated :nums, :sint64, 1
  end
  add_message "calculator.CalculatorResponse" do
    optional :result, :sint64, 1
  end
end

module Calculator
  CalculatorRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("calculator.CalculatorRequest").msgclass
  CalculatorResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("calculator.CalculatorResponse").msgclass
end
